### ISSUE TITLE
The peer could not join the channel.

### ISSUE THREAD

**Issue by josser** [IBM-Bluemix-Docs/blockchain#139]
Hi! 
I'm following tutorial https://cloud.ibm.com/docs/services/blockchain/howto?topic=blockchain-ibp-console-build-network#ibp-console-channels-create but on last step (5) I can't join peer to channel.

The only error it shows is: The peer could not join the channel.

What I can do to figure out the reason for this? 

Thank you and sorry if my english is bad

**Comment by josser** [comment]
Just repeated everything from first step and now I don't getting an error. Probably my mistake somewhere in forms.

**Comment by wan-yong** [comment]
I meet the same problem and the kubernetes log shows 
`[31m2019-03-12 05:18:16.316 UTC [main] InitCmd -> ERRO 001[0m Cannot run peer because cannot init crypto, folder "/certs/msp" does not exist`
