### ISSUE TITLE
Fix variable name mismatch for the connection profile JSON object

### ISSUE THREAD

**Issue by jeancarl** [IBM-Bluemix-Docs/blockchain#141]
Under `Step four: Using the connection profile to build a fabric gateway` of the `Run the Commercial Paper sample` section (https://cloud.ibm.com/docs/services/blockchain/howto?topic=blockchain-ibp-console-app#step-four-using-the-connection-profile-to-build-a-fabric-gateway), there is a variable name mismatch in the code.

<img width="1440" alt="screen shot 2019-03-05 at 4 19 13 pm" src="https://user-images.githubusercontent.com/1245985/53846619-7e4f9380-3f62-11e9-91d4-03d3f9fc9e23.png">

The second block shows an example of what your code may look like after the changes are made. However, `connectionProfile` is really named `ccp`.
```
const userName = 'user1';

// Load connection profile; will be used to locate a gateway
const ccpPath = path.resolve(__dirname, '../gateway/connection.json');
const ccpJSON = fs.readFileSync(ccpPath, 'utf8');
const ccp = JSON.parse(ccpJSON);

// Set connection options; identity and wallet
let connectionOptions = {
  identity: userName,
  wallet: wallet,
  discovery: { enabled: true, asLocalhost: false }
};

await gateway.connect(connectionProfile, connectionOptions);
```

Fix:

Replace the code snippet with:
```
const userName = 'user1';

// Load connection profile; will be used to locate a gateway
const ccpPath = path.resolve(__dirname, '../gateway/connection.json');
const ccpJSON = fs.readFileSync(ccpPath, 'utf8');
const connectionProfile = JSON.parse(ccpJSON);

// Set connection options; identity and wallet
let connectionOptions = {
  identity: userName,
  wallet: wallet,
  discovery: { enabled: true, asLocalhost: false }
};

await gateway.connect(connectionProfile, connectionOptions);
```

**Comment by wjzhengsh** [comment]
@jeancarl Thanks for your comments.  We have made updates to our doc and it will take effect during our next doc push.

You are always welcomed to providing your comments to the IBM Blockchain Platform documentation.  THANK YOU!
