### ISSUE TITLE
Add Melbourne to list of Enterprise Plan locations

### ISSUE THREAD

**Issue by andrewyuau** [IBM-Bluemix-Docs/blockchain#161]
Hi team,

There have been multiple public announcements that IBP is available in Melbourne: https://www.zdnet.com/article/ibm-blockchain-platform-now-live-in-melbourne/
https://www.coinspeaker.com/ibm-blockchain-melbourne/
https://cointelegraph.com/news/ibm-launches-blockchain-platform-on-cloud-service-in-melbourne

However, the official docs ( https://cloud.ibm.com/docs/services/blockchain/reference?topic=blockchain-ibp-regions-locations#ibp-regions-locations ) do not list Melbourne as one of the locations. Can Melbourne be added please?

**Comment by pamandrejko** [comment]
@andrewyuau Thank you for surfacing this issue. We are working to address the problem now.

**Comment by pamandrejko** [comment]
Content has been published here: https://cloud.ibm.com/docs/services/blockchain?topic=blockchain-ibp-regions-locations#ibp-regions-locations

**Comment by andrewyuau** [comment]
Thank you @pamandrejko I will close this.
