### ISSUE TITLE
shim.Error is not working 

### ISSUE THREAD

**Issue by hipraveen** [IBM-Bluemix-Docs/blockchain#166]
I am using below code in my chaincode ,
return shim.Error("ItemPrice and Quantity is not matched with totalAmount for Item code ")

but in API i am geting below error 

{
    "success": false,
    "message": "FAILED: Error: Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: {\"status\":500,\"payload\":{\"type\":\"Buffer\",\"data\":[]},\"peer\":{\"url\":\"grpcs://nf5c7da7f577642cc8afdae13b847f521-org1-peer1.us02.blockchain.ibm.com:31002\",\"name\":\"org1-peer1\",\"options\":{\"name\":\"org1-peer1\",\"grpc.http2.keepalive_time\":36000,\"grpc.keepalive_time_ms\":360000,\"grpc.http2.keepalive_timeout\":180000,\"grpc.keepalive_timeout_ms\":180000,\"grpc.http2.min_time_between_pings_ms\":120000,\"grpc.http2.max_pings_without_data\":1345000,\"grpc.keepalive_permit_without_calls\":100000,\"grpc.max_receive_message_length\":200000,\"request-timeout\":300000,\"grpc.max_send_message_length\":-1}},\"isProposalResponse\":true}"
}

**Comment by pamandrejko** [comment]
@hipraveen Thank you for your comment. Please open a support ticket so that your question can be properly addressed.

**Comment by pamandrejko** [comment]
No response from reporter so I am closing this issue for now.
