### ISSUE TITLE
Can't log into cloud solution manager

### ISSUE THREAD

**Issue by mikerault** [IBM-Bluemix-Docs/blockchain#169]
I get the error:
CWOAU0062E: The OAuth service provider could not redirect the request because the redirect URI was not valid. Contact your system administrator to resolve the problem.

When trying to access the service for blockhcain document store. Here is the URl call:

https://idaas.iam.ibm.com/idaas/oidc/endpoint/default/authorize?redirect_uri=https%3A%2F%2Fpbsa-prod.us-south.containers.mybluemix.net%2F703c9b46-3443-4a77-8cbf-7d5b555dbf37%2Fonboarding%2Fidentity%2Fv0%2Fauth%2Fsso%2Fcallback&scope=openid&state=1555080021317&nonce=1555080021317&access_type=online&login_hint=&prompt=select_account&response_type=id_token%20token&response_mode=form_post&claims=%7B%22id_token%22%3A%7B%22email_verified%22%3Anull%7D%7D&client_id=YmFkZGMwYmEtMWZkYS00

**Comment by mikerault** [comment]
Thanks for nothing, no help, no response, is this what clients can expect?

**Comment by pamandrejko** [comment]
@mikerault We apologize for the delay in response. This is not the correct document repo for the Blockchain document store.  I believe the documentation you are referring to is located here
https://cloud.ibm.com/docs/services/blockchain-document-store?topic=blockchain-document-store-what-s-new#what-s-new?

You would need to open your issue against this repo: 
https://github.com/IBM-Bluemix-Docs/blockchain-document-store/issues/new

I'll let you confirm.

**Comment by pamandrejko** [comment]
Closing an the submitter has not responded and this issue is against a different product.
