### ISSUE TITLE
Where can I find the Network resource limitation about Enterprise Plan

### ISSUE THREAD

**Issue by 09001413** [IBM-Bluemix-Docs/blockchain#170]
I read the doc and didn't find any description about the disk volume I can get when I have a Enterprise Plan. It's a very import point when our team make the decision, so could you please kindly show me where is the document?

**Comment by 09001413** [comment]
And if my ledger reached the disk volume limitation, then what should we do?

**Comment by pamandrejko** [comment]
Thank you for your comment. We are working to get an answer for you.

**Comment by pamandrejko** [comment]
@09001413 Currently there is no storage limitation on Enterprise Plan networks.

If you have specific questions or need to learn more we would be happy to work with you

**Comment by 09001413** [comment]
@pamandrejko Got it, thank you for your answer. Have a nice day!

**Comment by ibmmark** [comment]
@09001413 let me know if you wanted to discuss particular options on this item as there are a few right now.
