### ISSUE TITLE
Correct link for IBP Locations

### ISSUE THREAD

**Issue by andrewyuau** [IBM-Bluemix-Docs/blockchain#178]
At https://cloud.ibm.com/docs/services/blockchain?topic=blockchain-enterprise-plan-about#enterprise-plan-about , in "For a list of available geographies, see IBM Blockchain Platform locations.", the link is broken. It should be https://cloud.ibm.com/docs/services/blockchain?topic=blockchain-ibp-regions-locations#ibp-regions-locations .

**Comment by yingmsky** [comment]
@pama-ibm @wjzheng FYI

**Comment by wjzhengsh** [comment]
Fixed.  @andrewyuau @yingmsky Please check.  Thanks for your comment!

**Comment by andrewyuau** [comment]
Thanks!
