### ISSUE TITLE
Need to hide the source code but to show the link reference.

### ISSUE THREAD

**Issue by SandySun2000** [IBM-Bluemix-Docs/blockchain#196]
https://cloud.ibm.com/docs/services/blockchain?topic=blockchain-dev-app#dev-app-enroll

Need to hide the source code, but only expose the link reference. 

If you don't have a blockchain network on IBM Cloud, you need to create one with either a Starter or Enterprise Membership Plan. For more information, see Creating a Starter Plan network or [Creating an Enterprise Plan network](/docs/services/blockchain/get_start.html

**Comment by pamandrejko** [comment]
Nancy could you take a look at this one?

**Comment by pamandrejko** [comment]
PR: https://github.com/IBM-Bluemix-Docs/blockchain/pull/197

**Comment by pamandrejko** [comment]
@SandySun2000 The link has been fixed. Can you verify and close this issue if you are satisfied? https://cloud.ibm.com/docs/services/blockchain/howto?topic=blockchain-dev-app#dev-app-prerequisites

**Comment by SandySun2000** [comment]
I verified the change, and the doc looks good now.
