### ISSUE TITLE
Deploying Certificate authority on IBM-ICP

### ISSUE THREAD

**Issue by harsha544** [IBM-Bluemix-Docs/blockchain#198]
URL https://cloud.ibm.com/docs/services/blockchain-icp-102?topic=blockchain-icp-102-ca-deploy#ca-deploy is no longer accessible

**Comment by pamandrejko** [comment]
@harsha544 Thank you. We are in the process of updating our repo for new content and during that time you may experience some broken links. We are working to address this as quickly as possible.

**Comment by pamandrejko** [comment]
The link should work now, please try again. Thank you for sharing this with us.

**Comment by harsha544** [comment]
Thank you, I can confirm it's working now.
