### ISSUE TITLE
Re. "Aw, Snap!" page crashes and other page loading errors

### ISSUE THREAD

**Issue by pvrbharg** [IBM-Bluemix-Docs/blockchain#219]
The following URL keeps giving this error every time while reviewing the pricing example - using every browser - Firefox, Chrome, MS Edge. Unless we have a fix for this issue - this is a useless webpage - that is critical for everyone. I am using WIndows 10 laptop. 

![image](https://user-images.githubusercontent.com/5838902/60995210-10581600-a320-11e9-9066-bc6bd412f1d9.png)

Thanks.
[WebPageDisplayIssue.zip](https://github.com/IBM-Bluemix-Docs/blockchain/files/3379162/WebPageDisplayIssue.zip)

**Comment by nikhil550** [comment]
Not sure what is in the zip file. Can you send me the link?

**Comment by pvrbharg** [comment]
You would get the answer by seeing what is in the zip, Nikhil! Did you try to see what is in the zip? Why do you think I took trouble to create the zip in the first place?

**Comment by nikhil550** [comment]
https://cloud.ibm.com/docs/services/blockchain?topic=blockchain-ibp-saas-pricing#ibp-saas-pricing-scenarios. I tried to recreate this issue on firefox and chrome and did not run into this issue.

There are no animations, gifs, or other images in this portion of the documentation. I do not know why there would be an issue with this section? Could you retest and send some browser logs if you experience again?

**Comment by pvrbharg** [comment]
Do you want me to demo this to you? It happens everytime on my machine with 3 browsers. You can collect whatever logs you want or debug directly on my laptop. Let me know your IBM email and I can webx with you to show you this issue.

I would not have this issue closed - just because you can replicate this or it does not happen on our laptop. 

Please advise. Thanks.

**Comment by pamandrejko** [comment]
Thank you for reporting this issue. One of our developers was able to recreate it on his WIndows machine. We are currently investigating.

**Comment by pamandrejko** [comment]
@sefuhrer

**Comment by pvrbharg** [comment]
Dear Pam, You are my hero and thank you so much for getting rid of this nuisance for everyone. Your fix accurately took care of my issue and I am good. Regards.

**Comment by pvrbharg** [comment]
We can close this issue now. I am good on my Windows 10 laptop with all 3 browsers! Great work and help. Thank you again Pam!
