### ISSUE TITLE
Starter Plan documentation should include steps to create REST endpoints

### ISSUE THREAD

**Issue by sanjay-saxena** [IBM-Bluemix-Docs/blockchain#24]
Currently, there are steps provided to help a developer create REST endpoints once the business network is started on the IBM Starter Plan instance.

Developers need to download the connection profile and use the admin-card created in the prior steps to be able to start the `composer-rest-server` to create REST endpoints for the deployed network. These steps are not intuitive and can easily flummox a developer. It would be good to have steps explicitly specified as part of the Starter Plan documentation.

**Comment by wjzhengsh** [comment]
Close this issue for now as we provide limited support to Composer now.
