### ISSUE TITLE
Update documentation to install Hyperledger Composer 0.18.1

### ISSUE THREAD

**Issue by sanjay-saxena** [IBM-Bluemix-Docs/blockchain#25]
This [link](https://console.bluemix.net/docs/services/blockchain/develop_install.html#installing-a-development-environment) instructs developers to install `composer-cli@next`. Which results in the installation of the latest Hyperledger Composer.

However, IBM Starter Plan is not compatible with the latest Hyperledger Composer. It seems like Hyperledger Composer 0.18.1 is the version that needs to be installed. The documentation should be fixed to include the correct version of Hyperledger Composer as part of the install steps.

**Comment by horeaporutiu** [comment]
Can be closed. Issue was addressed with this PR: https://github.com/IBM-Bluemix-Docs/blockchain/pull/23
