### ISSUE TITLE
Include instructions to start composer-rest-server on IBM Cloud

### ISSUE THREAD

**Issue by sanjay-saxena** [IBM-Bluemix-Docs/blockchain#26]
It would be good to provide detailed instructions based on Hyperledger Composer 0.18.1 to use `composer-rest-server` directly on IBM Cloud(instead of locally) to generate REST endpoints using the cloud-based card store that is available as part of the Starter Plan instance.

**Comment by wjzhengsh** [comment]
@EdProsser Would you take a look?

**Comment by wjzhengsh** [comment]
Close this issue for now as we provide limited support to Composer now.
