### ISSUE TITLE
Use UI to perform Step 3 -- Adding the certificates to the Starter Plan instance

### ISSUE THREAD

**Issue by sanjay-saxena** [IBM-Bluemix-Docs/blockchain#29]
In this [link](https://console.bluemix.net/docs/services/blockchain/develop_starter.html#deploying-a-business-networks-on-starter-plan), `curl` is used to perform the smaller steps that make up `Step 3: Adding the certificates to the Starter Plan instance`. This requires the developer to figure out various placeholder tokens that need to be substituted before issuing the `curl` command. Also, the steps are very confusing as step 3.2 says `Stop the peers by using the following API call`. Does it mean stop the peers in current organization? Or, does it mean stop the peers in all/both the organizations? 

And, even if one gets past step 3.2 with `{"message":"ok"}`, they will be blocked by step 3.4 used to synchronize the certs as it results in `{"error":"route not found"}`.

Confusion like this can be avoided if UI is used to let the developers know exactly what they are supposed to.

**Comment by sanjay-saxena** [comment]
Related [issue](https://github.com/IBM-Blockchain/vehicle-manufacture/issues/33) filed against vehicle-manufacture repo.

**Comment by horeaporutiu** [comment]
Issue can be closed, as it resolved with this PR: https://github.com/IBM-Bluemix-Docs/blockchain/pull/23
