### ISSUE TITLE
Multiple organizations -- Clarify the org/connection-profile to be used in the steps

### ISSUE THREAD

**Issue by sanjay-saxena** [IBM-Bluemix-Docs/blockchain#30]
Since each organization has it's own connection profile, this [doc](https://console.bluemix.net/docs/services/blockchain/develop_starter.html#deploying-a-business-networks-on-starter-plan) should clarify the following:

- Identify the organization and the corresponding connection-profile that needs to be used for each of the steps.
- Identify steps that need to be performed multiple times using different connection-profiles. For example, if there are two orgs, I would assume that there will be `org1-admin` and `org2-admin` cards that need to be created(using different connection-profiles) and imported. And, each of the admins will have different certs(public and private keys).
- Are there steps that need to be performed for each peer in every organization?

**Comment by EdProsser** [comment]
Ok, this might have some legs. Adding some information clarifying best practice for multi-orgs.

**Comment by wjzhengsh** [comment]
I believe this was addressed late last year.  Close this issue for now as we provide limited support to Composer now.
