### ISSUE TITLE
PeerAdmin and NetworkAdmin using the same public/private keys

### ISSUE THREAD

**Issue by sanjay-saxena** [IBM-Bluemix-Docs/blockchain#31]
In the instructions for [deploying  business networks on Starter Plan](https://console.bluemix.net/docs/services/blockchain/develop_starter.html#deploying-a-business-networks-on-starter-plan), it seems like the both Peer-Admin (created in Step 4) and the Network-Admin (created in Step 5) seem to be using the same public/private keys.

As per current instructions, it appears that the Peer-Admin and the Network-Admin(for at least one org) will be the same. If this assumption is incorrect, then there is a potential security hole. Do we need separate set of certs for Peer-Admin and all the Network-Admin? If yes, the instructions should be updated accordingly.

**Comment by EdProsser** [comment]
@pamandrejko This doesn't appear to be a docs issue. I think it needs some discussion with others.

**Comment by wjzhengsh** [comment]
Close this issue for now as we provide limited support to Composer now.
