### ISSUE TITLE
Enterprise v.1.1

### ISSUE THREAD

**Issue by mataide** [IBM-Bluemix-Docs/blockchain#47]
Why you says to use composer 0.16.x on Enterprise?
https://github.com/IBM-Bluemix-Docs/blockchain/blob/master/develop_install.md

0.16.x are only for Fabric 1.0.

**Comment by wjzhengsh** [comment]
@EdProsser Would you confirm?

**Comment by EdProsser** [comment]
@mataide @wjzhengsh While you are correct that composer version 0.16.x is only for Fabric 1.0, all enterprise plan instances created at Fabric v1.0 have not yet been migrated to Fabric 1.1. 

That said, all new instances of Enterprise plan are using Fabric 1.1, so the recommended composer version should also change.

**Comment by wjzhengsh** [comment]
Fixed.
